# Generated by Django 4.2.5 on 2023-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above read the blog post', max_length=255),
        ),
    ]
